#!/usr/bin/env python3
"""Internationalization support for SkillShepard"""

TRANSLATIONS = {
    'en': {
        # CLI messages
        'cli_description': 'SkillShepard - Skill Security Scanner',
        'cli_skill_dir_help': 'Skills root directory (auto-detected if not specified)',
        'cli_lang_help': 'Output language (en: English, ja: Japanese)',
        'cli_install_help': 'Security check and install Skill',
        'cli_install_path_help': 'Skill path to install',
        'cli_scan_only_help': 'Only scan, do not install',
        'cli_output_help': 'Output file (default: stdout)',
        'cli_yes_help': 'Skip confirmation for overwrite',
        'cli_scan_help': 'Batch scan existing Skills',
        'cli_scan_dir_help': 'Target directory to scan (default: auto-detected skills root)',
        'cli_info_help': 'Show skill directory info',

        # Info command
        'info_title': 'SkillShepard Directory Info',
        'info_script_location': 'Script location',
        'info_skill_directory': 'Skill directory',
        'info_skills_root': 'Skills root',
        'info_not_detected': '(not detected)',

        # Install messages
        'security_issues_found': 'Security issues found. Report saved to: {path}',
        'installation_aborted': 'Installation aborted due to security issues.',
        'no_issues_in': 'No security issues found in: {name}',
        'skill_exists': "Skill '{name}' already exists at: {path}",
        'overwrite_prompt': 'Overwrite? [y/N]: ',
        'installation_cancelled': 'Installation cancelled.',
        'installed_with_warnings': 'Installed with warnings: {path}',
        'no_security_issues': 'No security issues found.',
        'installed': 'Installed: {path}',
        'report_saved': 'Report saved to: {path}',

        # Error messages
        'error_skills_dir_not_detected': 'Error: Could not detect skills directory. Use --skill-dir to specify.',
        'error_skills_dir_specify': 'Error: Could not detect skills directory. Please specify a directory.',
        'error_prefix': 'Error: {message}',

        # Report - Severity
        'severity_high': 'HIGH',
        'severity_medium': 'MEDIUM',
        'severity_low': 'LOW',

        # Report - Status
        'status_passed': 'PASSED',
        'status_warning': 'WARNING',
        'status_blocked': 'BLOCKED',

        # Report - Issue types
        'type_command_injection': 'Command Injection',
        'type_path_manipulation': 'Path Manipulation',
        'type_secret_exposure': 'Secret Exposure',
        'type_external_communication': 'External Communication',
        'type_privilege_escalation': 'Privilege Escalation',
        'type_dangerous_command': 'Dangerous Command',
        'type_insecure_default': 'Insecure Default',
        'type_insecure_deserialization': 'Insecure Deserialization',
        'type_information_disclosure': 'Information Disclosure',
        'type_dependency_risk': 'Dependency Risk',
        'type_prompt_injection': 'Prompt Injection',
        'type_external_data_fetch': 'External Data Fetch',
        'type_supply_chain': 'Supply Chain Risk',

        # Report - Labels
        'report_title': 'SkillShepard Security Report',
        'report_summary': 'Summary',
        'report_skill': 'Skill',
        'report_path': 'Path',
        'report_status': 'Status',
        'report_issues_found': 'Issues Found',
        'report_no_issues': 'No security issues detected.',
        'report_issue_breakdown': 'Issue Breakdown',
        'report_severity': 'Severity',
        'report_count': 'Count',
        'report_high': 'High',
        'report_medium': 'Medium',
        'report_low': 'Low',
        'report_issues': 'Issues',
        'report_file': 'File',
        'report_line': 'line',
        'report_issue': 'Issue',
        'report_code': 'Code',
        'report_recommendation': 'Recommendation',
        'report_action_required': 'Action Required',
        'report_action_blocked': 'This skill has HIGH severity issues and should NOT be imported.',
        'report_recommendation_title': 'Recommendation',
        'report_review_warnings': 'Review the warnings above before importing.',
        'report_generated_by': 'Generated by SkillShepard',

        # Scanner recommendations
        'rec_command_injection': 'Use subprocess.run() with shell=False and pass arguments as a list',
        'rec_path_manipulation': 'Limit path scope',
        'rec_secret_exposure': 'Use environment variables (os.environ.get())',
        'rec_external_communication': 'Verify external endpoints and use HTTPS',
        'rec_privilege_escalation': 'Limit allowed-tools scope',
        'rec_dangerous_command': 'Avoid dangerous system commands',
        'rec_insecure_default': 'Enable security settings',
        'rec_insecure_deserialization': 'Use safe alternatives (e.g., yaml.safe_load(), json instead of pickle)',
        'rec_information_disclosure': 'Remove sensitive data from logs and output',
        'rec_dependency_risk': 'Install packages from official registries with pinned versions',
        'rec_prompt_injection': 'Remove prompt injection patterns - these could manipulate agent behavior',
        'rec_external_data_fetch': 'External content may contain malicious instructions - validate and sanitize fetched data',
        'rec_supply_chain': 'Avoid executing remote scripts - download, review, then execute locally',
    },

    'ja': {
        # CLI messages
        'cli_description': 'SkillShepard - Skillセキュリティスキャナー',
        'cli_skill_dir_help': 'Skillsルートディレクトリ（未指定時は自動検出）',
        'cli_lang_help': '出力言語 (en: 英語, ja: 日本語)',
        'cli_install_help': 'セキュリティチェックとSkillのインストール',
        'cli_install_path_help': 'インストールするSkillのパス',
        'cli_scan_only_help': 'スキャンのみ実行（インストールしない）',
        'cli_output_help': '出力ファイル（デフォルト: 標準出力）',
        'cli_yes_help': '上書き確認をスキップ',
        'cli_scan_help': '既存Skillの一括スキャン',
        'cli_scan_dir_help': 'スキャン対象ディレクトリ（デフォルト: 自動検出）',
        'cli_info_help': 'ディレクトリ情報を表示',

        # Info command
        'info_title': 'SkillShepard ディレクトリ情報',
        'info_script_location': 'スクリプト位置',
        'info_skill_directory': 'Skillディレクトリ',
        'info_skills_root': 'Skillsルート',
        'info_not_detected': '（未検出）',

        # Install messages
        'security_issues_found': 'セキュリティ問題が見つかりました。レポート保存先: {path}',
        'installation_aborted': 'セキュリティ問題のためインストールを中止しました。',
        'no_issues_in': 'セキュリティ問題は見つかりませんでした: {name}',
        'skill_exists': "Skill '{name}' は既に存在します: {path}",
        'overwrite_prompt': '上書きしますか？ [y/N]: ',
        'installation_cancelled': 'インストールをキャンセルしました。',
        'installed_with_warnings': '警告付きでインストール完了: {path}',
        'no_security_issues': 'セキュリティ問題は見つかりませんでした。',
        'installed': 'インストール完了: {path}',
        'report_saved': 'レポート保存先: {path}',

        # Error messages
        'error_skills_dir_not_detected': 'エラー: Skillsディレクトリを検出できませんでした。--skill-dirで指定してください。',
        'error_skills_dir_specify': 'エラー: Skillsディレクトリを検出できませんでした。ディレクトリを指定してください。',
        'error_prefix': 'エラー: {message}',

        # Report - Severity
        'severity_high': '高',
        'severity_medium': '中',
        'severity_low': '低',

        # Report - Status
        'status_passed': '合格',
        'status_warning': '警告',
        'status_blocked': 'ブロック',

        # Report - Issue types
        'type_command_injection': 'コマンドインジェクション',
        'type_path_manipulation': 'パス操作',
        'type_secret_exposure': 'シークレット露出',
        'type_external_communication': '外部通信',
        'type_privilege_escalation': '権限昇格',
        'type_dangerous_command': '危険なコマンド',
        'type_insecure_default': '安全でないデフォルト設定',
        'type_insecure_deserialization': '安全でないデシリアライゼーション',
        'type_information_disclosure': '情報漏洩',
        'type_dependency_risk': '依存関係リスク',
        'type_prompt_injection': 'プロンプトインジェクション',
        'type_external_data_fetch': '外部データ取得',
        'type_supply_chain': 'サプライチェーンリスク',

        # Report - Labels
        'report_title': 'SkillShepard セキュリティレポート',
        'report_summary': '概要',
        'report_skill': 'Skill',
        'report_path': 'パス',
        'report_status': 'ステータス',
        'report_issues_found': '検出された問題',
        'report_no_issues': 'セキュリティ問題は検出されませんでした。',
        'report_issue_breakdown': '問題の内訳',
        'report_severity': '深刻度',
        'report_count': '件数',
        'report_high': '高',
        'report_medium': '中',
        'report_low': '低',
        'report_issues': '検出された問題',
        'report_file': 'ファイル',
        'report_line': '行',
        'report_issue': '問題',
        'report_code': 'コード',
        'report_recommendation': '推奨事項',
        'report_action_required': '対応が必要',
        'report_action_blocked': 'このSkillには高深刻度の問題があり、インポートすべきではありません。',
        'report_recommendation_title': '推奨事項',
        'report_review_warnings': 'インポート前に上記の警告を確認してください。',
        'report_generated_by': 'SkillShepard により生成',

        # Scanner recommendations
        'rec_command_injection': 'subprocess.run()をshell=Falseで使用し、引数をリストとして渡してください',
        'rec_path_manipulation': 'パスのスコープを制限してください',
        'rec_secret_exposure': '環境変数を使用してください（os.environ.get()）',
        'rec_external_communication': '外部エンドポイントを確認し、HTTPSを使用してください',
        'rec_privilege_escalation': 'allowed-toolsのスコープを制限してください',
        'rec_dangerous_command': '危険なシステムコマンドを避けてください',
        'rec_insecure_default': 'セキュリティ設定を有効にしてください',
        'rec_insecure_deserialization': '安全な代替手段を使用してください（例: yaml.safe_load()、pickleの代わりにjson）',
        'rec_information_disclosure': 'ログや出力から機密データを削除してください',
        'rec_dependency_risk': '公式レジストリからバージョンを固定してパッケージをインストールしてください',
        'rec_prompt_injection': 'プロンプトインジェクションパターンを削除してください - エージェントの動作を操作される可能性があります',
        'rec_external_data_fetch': '外部コンテンツには悪意のある命令が含まれている可能性があります - 取得したデータを検証・サニタイズしてください',
        'rec_supply_chain': 'リモートスクリプトの実行を避けてください - ダウンロードして確認後、ローカルで実行してください',
    }
}


class I18n:
    """Internationalization helper class"""

    def __init__(self, lang: str = 'en'):
        self.lang = lang if lang in TRANSLATIONS else 'en'
        self.translations = TRANSLATIONS[self.lang]

    def t(self, key: str, **kwargs) -> str:
        """Get translated string with optional format arguments"""
        text = self.translations.get(key, TRANSLATIONS['en'].get(key, key))
        if kwargs:
            return text.format(**kwargs)
        return text

    def get_type_key(self, issue_type: str) -> str:
        """Convert issue type to translation key"""
        return f'type_{issue_type}'

    def get_rec_key(self, issue_type: str) -> str:
        """Convert issue type to recommendation translation key"""
        return f'rec_{issue_type}'
