#!/usr/bin/env python3
"""Report generators for SkillShepard scan results"""

import json
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from scanner import ScanReport, ScanResult


class JsonReporter:
    def generate(self, report: "ScanReport") -> str:
        data = {
            "scan_date": report.scan_date,
            "skills_scanned": report.skills_scanned,
            "issues_found": report.issues_found,
            "results": [{
                "skill_name": r.skill_name, "path": r.path, "status": r.status,
                "issues": [{"severity": i.severity, "type": i.type, "file": i.file,
                           "line": i.line, "message": i.message,
                           "code_snippet": i.code_snippet, "recommendation": i.recommendation}
                          for i in r.issues]
            } for r in report.results]
        }
        return json.dumps(data, indent=2, ensure_ascii=False)


class MarkdownReporter:
    SEVERITY_EMOJI = {'high': '🔴', 'medium': '🟡', 'low': '🔵'}
    SEVERITY_LABEL = {'high': 'HIGH', 'medium': 'MEDIUM', 'low': 'LOW'}
    STATUS_LABEL = {'ok': '✅ PASSED', 'warning': '⚠️ WARNING', 'blocked': '🚫 BLOCKED'}
    TYPE_LABEL = {
        'command_injection': 'Command Injection', 'path_manipulation': 'Path Manipulation',
        'secret_exposure': 'Secret Exposure', 'external_communication': 'External Communication',
        'privilege_escalation': 'Privilege Escalation', 'dangerous_command': 'Dangerous Command',
        'insecure_default': 'Insecure Default', 'insecure_deserialization': 'Insecure Deserialization',
        'information_disclosure': 'Information Disclosure', 'dependency_risk': 'Dependency Risk',
        'prompt_injection': 'Prompt Injection', 'external_data_fetch': 'External Data Fetch',
        'supply_chain': 'Supply Chain Risk',
    }

    def generate(self, result: "ScanResult") -> str:
        lines = [
            "# SkillShepard Security Report", "",
            "## Summary", "",
            f"- **Skill**: `{result.skill_name}`",
            f"- **Path**: `{result.path}`",
            f"- **Status**: {self.STATUS_LABEL.get(result.status, result.status)}",
            f"- **Issues Found**: {len(result.issues)}", ""
        ]

        if not result.issues:
            lines.append("No security issues detected.")
            return '\n'.join(lines)

        high = sum(1 for i in result.issues if i.severity == 'high')
        med = sum(1 for i in result.issues if i.severity == 'medium')
        low = sum(1 for i in result.issues if i.severity == 'low')

        lines += [
            "### Issue Breakdown", "",
            "| Severity | Count |", "|----------|-------|",
            f"| {self.SEVERITY_EMOJI['high']} High | {high} |",
            f"| {self.SEVERITY_EMOJI['medium']} Medium | {med} |",
            f"| {self.SEVERITY_EMOJI['low']} Low | {low} |",
            "", "---", "", "## Issues", ""
        ]

        sorted_issues = sorted(result.issues, key=lambda x: {'high': 0, 'medium': 1, 'low': 2}.get(x.severity, 3))

        for i, issue in enumerate(sorted_issues, 1):
            emoji = self.SEVERITY_EMOJI.get(issue.severity, '⚪')
            label = self.SEVERITY_LABEL.get(issue.severity, issue.severity.upper())
            type_label = self.TYPE_LABEL.get(issue.type, issue.type)

            lines += [
                f"### {i}. [{emoji} {label}] {type_label}", "",
                f"**File**: `{issue.file}`" + (f" (line {issue.line})" if issue.line else ""), "",
                f"**Issue**: {issue.message}", ""
            ]

            if issue.code_snippet:
                lines += ["**Code**:", "```", issue.code_snippet, "```", ""]
            if issue.recommendation:
                lines += [f"**Recommendation**: {issue.recommendation}", ""]
            lines += ["---", ""]

        if result.status == 'blocked':
            lines += ["## Action Required", "",
                     "This skill has HIGH severity issues and should NOT be imported.", ""]
        elif result.status == 'warning':
            lines += ["## Recommendation", "",
                     "Review the warnings above before importing.", ""]

        lines += ["---", "*Generated by SkillShepard*"]
        return '\n'.join(lines)
